package l1j.server.server.model.identity;

public class L1ItemId {

	public static final int POTION_OF_HASTE_SELF = 40013;
	public static final int B_POTION_OF_HASTE_SELF = 140013;
	public static final int POTION_OF_GREATER_HASTE_SELF = 40018;
	public static final int B_POTION_OF_GREATER_HASTE_SELF = 140018;
	public static final int POTION_OF_EMOTION_BRAVERY = 40014;
	public static final int B_POTION_OF_EMOTION_BRAVERY = 140014;
	public static final int POTION_OF_REINFORCED_CASE = 41415;
	public static final int W_POTION_OF_EMOTION_BRAVERY = 49305;
	public static final int DEVILS_BLOOD = 40031;
	public static final int COIN_OF_REPUTATION = 40733;
	public static final int ELVEN_WAFER = 40068;
	public static final int B_ELVEN_WAFER = 140068;
	public static final int W_POTION_OF_FOREST = 49304;
	public static final int FORBIDDEN_FRUIT = 49158;
	public static final int CHOCOLATE_CAKE = 49138;
	public static final int POTION_OF_HEALING = 40010;
	public static final int B_POTION_OF_HEALING = 140010;
	public static final int C_POTION_OF_HEALING = 240010;
	public static final int POTION_OF_EXTRA_HEALING = 40011;
	public static final int B_POTION_OF_EXTRA_HEALING = 140011;
	public static final int POTION_OF_GREATER_HEALING = 40012;
	public static final int B_POTION_OF_GREATER_HEALING = 140012;
	public static final int CONDENSED_POTION_OF_HEALING = 40019;
	public static final int CONDENSED_POTION_OF_EXTRA_HEALING = 40020;
	public static final int CONDENSED_POTION_OF_GREATER_HEALING = 40021;
	public static final int POTION_OF_MANA = 40015;
	public static final int B_POTION_OF_MANA = 140015;
	public static final int POTION_OF_EMOTION_WISDOM = 40016;
	public static final int B_POTION_OF_EMOTION_WISDOM = 140016;
	public static final int POTION_OF_CURE_POISON = 40017;
	public static final int POTION_OF_BLINDNESS = 40025;
	public static final int SCROLL_OF_ENCHANT_ARMOR = 40074;
	public static final int B_SCROLL_OF_ENCHANT_ARMOR = 140074;
	public static final int C_SCROLL_OF_ENCHANT_ARMOR = 240074;
	public static final int SCROLL_OF_ENCHANT_WEAPON = 40087;
	public static final int B_SCROLL_OF_ENCHANT_WEAPON = 140087;
	public static final int C_SCROLL_OF_ENCHANT_WEAPON = 240087;
	public static final int SCROLL_OF_ENCHANT_QUEST_WEAPON = 40660;
	public static final int POTION_OF_EXP_150 = 47000;
	public static final int POTION_OF_EXP_175 = 47001;
	public static final int POTION_OF_EXP_200 = 47002;
	public static final int POTION_OF_EXP_225 = 47003;
	public static final int POTION_OF_EXP_250 = 47004;
	public static final int BLESS_OF_MAZU = 47005;
	public static final int POTION_OF_BATTLE = 47006;
	public static final int SCROLL_FOR_STRENGTHENING_HP = 47007;
	public static final int SCROLL_FOR_STRENGTHENING_MP = 47008;
	public static final int SCROLL_FOR_ENCHANTING_BATTLE = 47009;
	public static final int POTION_OF_WONDER_DRUG = 49315;
	public static final int ADENA = 40308;

    public static final int BloodExtractor = 250013;
    public static final int BloodSample = 250015;
    public static final int SummoningStone = 250014;
    public static final int SoulShard = 250016;
}
